[package]
name = "day_11"
version = "0.1.0"
edition = "2021"
default-run = "day_11"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#[profile.release]
#opt-level = 3

[dependencies]
rustutils = { path = "../rustutils" }